"""Parity tests between ``backend.metadata`` (Alembic source) and the live
``backend.database.init_database`` schema.

The goal of phase 1 is for the SQLAlchemy schema to faithfully describe what
``init_database`` actually creates. These tests are the gate that proves it.

Two checks:

1. ``alembic upgrade head`` against a fresh sqlite DB produces the same set
   of tables, columns and indexes (by name) as ``init_database``.
2. ``alembic upgrade head --sql`` against a MySQL URL renders DDL containing
   the InnoDB / utf8mb4 markers we care about.
"""
from __future__ import annotations

import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = REPO_ROOT / "backend"


def _introspect(db_path: Path) -> dict[str, dict]:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' AND name != 'alembic_version'"
    )
    tables = {r["name"] for r in cur.fetchall()}

    schema: dict[str, dict] = {}
    for t in tables:
        cur.execute(f"PRAGMA table_info({t})")
        cols = {row["name"] for row in cur.fetchall()}
        cur.execute(f"PRAGMA index_list({t})")
        idxs = {row["name"] for row in cur.fetchall() if not row["name"].startswith("sqlite_")}
        schema[t] = {"columns": cols, "indexes": idxs}
    conn.close()
    return schema


def _build_init_database_schema(tmpdir: Path) -> dict[str, dict]:
    """Run ``init_database`` against a temp sqlite file and return introspection."""
    db_file = tmpdir / "init-db.sqlite"
    env = os.environ.copy()
    env["DATABASE_PATH"] = str(db_file)
    env["DEPLOY_MODE"] = "single_tenant"
    # Run init_database in a subprocess so the module-level DATABASE_PATH
    # captures the temp path.
    code = (
        "import sys; sys.path.insert(0, %r);"
        "from backend.database import init_database; init_database()"
        % str(REPO_ROOT)
    )
    subprocess.run(
        [sys.executable, "-c", code], env=env, cwd=str(REPO_ROOT), check=True
    )
    return _introspect(db_file)


def _build_alembic_schema(tmpdir: Path) -> dict[str, dict]:
    db_file = tmpdir / "alembic-db.sqlite"
    env = os.environ.copy()
    env["DATABASE_URL"] = f"sqlite:///{db_file}"
    subprocess.run(
        ["alembic", "upgrade", "head"],
        cwd=str(BACKEND_DIR),
        env=env,
        check=True,
        capture_output=True,
    )
    return _introspect(db_file)


@pytest.fixture(scope="module")
def schemas():
    # `schemas` builds a sqlite-only comparison (init_database is a no-op on
    # MySQL since alembic owns the schema there). Tests using this fixture
    # auto-skip on non-sqlite DATABASE_URL via this guard. The independent
    # MySQL DDL render test does NOT use this fixture and still runs.
    db_url = os.environ.get('DATABASE_URL', '')
    if db_url and not db_url.startswith('sqlite'):
        pytest.skip("init_database parity is sqlite-only")
    if shutil.which("alembic") is None:
        pytest.skip("alembic CLI not on PATH")
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        return {
            "alembic": _build_alembic_schema(tmp),
            "init": _build_init_database_schema(tmp),
        }


def test_table_names_match(schemas):
    a = set(schemas["alembic"].keys())
    i = set(schemas["init"].keys())
    only_alembic = a - i
    only_init = i - a
    assert not only_alembic and not only_init, (
        f"Schema drift between Alembic metadata and init_database():\n"
        f"  only in alembic: {sorted(only_alembic)}\n"
        f"  only in init_database: {sorted(only_init)}"
    )


def test_columns_match_per_table(schemas):
    diffs = []
    for table in sorted(set(schemas["alembic"]) & set(schemas["init"])):
        a_cols = schemas["alembic"][table]["columns"]
        i_cols = schemas["init"][table]["columns"]
        if a_cols != i_cols:
            diffs.append(
                f"{table}: only-alembic={sorted(a_cols - i_cols)} "
                f"only-init={sorted(i_cols - a_cols)}"
            )
    assert not diffs, "Column drift:\n  " + "\n  ".join(diffs)


def test_indexes_present_in_alembic(schemas):
    """Every index built by init_database must exist in the Alembic schema.

    Alembic may have a few extra autogenerated unique indexes (e.g. for
    UNIQUE constraints), so we only assert one direction.
    """
    missing: list[str] = []
    for table in sorted(set(schemas["alembic"]) & set(schemas["init"])):
        i_idx = {n for n in schemas["init"][table]["indexes"] if n.startswith("idx_")}
        a_idx = schemas["alembic"][table]["indexes"]
        gap = i_idx - a_idx
        if gap:
            missing.append(f"{table}: missing {sorted(gap)}")
    assert not missing, "Indexes missing from Alembic metadata:\n  " + "\n  ".join(missing)


def test_mysql_ddl_renders_with_utf8mb4_and_check():
    if shutil.which("alembic") is None:
        pytest.skip("alembic CLI not on PATH")
    env = os.environ.copy()
    env["DATABASE_URL"] = "mysql+pymysql://u:p@h/db?charset=utf8mb4"
    out = subprocess.run(
        ["alembic", "upgrade", "head", "--sql"],
        cwd=str(BACKEND_DIR),
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )
    ddl = out.stdout
    for marker in ("utf8mb4_0900_ai_ci", "AUTO_INCREMENT", "JSON", "CHECK ("):
        assert marker in ddl, f"MySQL DDL missing marker {marker!r}"
