"""initial schema

Revision ID: 1826e23835b6
Revises: 
Create Date: 2026-05-09 12:21:03.280387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1826e23835b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_auth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matched_subject_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("decision IN ('pass','deny','skipped')", name='ck_face_auth_logs_decision'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_auth_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('face_auth_logs', schema=None) as batch_op:
        batch_op.create_index('idx_face_logs_query', ['tenant_id', 'created_at'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('erp_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('test_passed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_erp_providers_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_providers')),
    sa.UniqueConstraint('provider_name', name=op.f('uq_erp_providers_provider_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('face_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_face_subjects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_subjects')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('face_subjects', schema=None) as batch_op:
        batch_op.create_index('idx_face_subjects_tenant', ['tenant_id', 'is_active'], unique=False)

    op.create_table('tenant_face_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('auth_token', sa.String(length=255), nullable=True),
    sa.Column('embedding_model_tag', sa.String(length=64), nullable=True),
    sa.Column('min_confidence', sa.Float(), server_default='0.65', nullable=False),
    sa.Column('verify_mode', sa.String(length=16), server_default='interface', nullable=False),
    sa.Column('created_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("mode IN ('local','lan')", name='ck_tenant_face_config_mode'),
    sa.CheckConstraint("verify_mode IN ('session','interface')", name='ck_tenant_face_config_verify_mode'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_face_config_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_face_config')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_face_config_tenant_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='view', nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_tenant', ['tenant_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_warehouses_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('slug', name=op.f('uq_warehouses_slug')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index('idx_warehouses_tenant', ['tenant_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='operate', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_keys_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_api_keys_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_api_keys_tenant', ['tenant_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_supplier', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_customer', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_contacts_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_contacts_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_tenant', ['tenant_id'], unique=False)

    op.create_table('face_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('model_tag', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('source_image_b64', sa.Text(), nullable=True),
    sa.Column('applies_to_warehouse_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('enrolled_at', sa.String(length=32), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('enrolled_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['face_subjects.id'], name=op.f('fk_face_enrollments_subject_id_face_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_face_enrollments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_enrollments')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.create_index('idx_face_enroll', ['tenant_id', 'model_tag', 'is_active'], unique=False)
        batch_op.create_index('idx_face_enroll_subject', ['subject_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=True),
    sa.Column('unit', sa.String(length=16), server_default='个', nullable=True),
    sa.Column('safe_stock', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_materials_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_materials_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('sku', name=op.f('uq_materials_sku')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('idx_materials_sku_wh', ['sku', 'warehouse_id'], unique=True)
        batch_op.create_index('idx_materials_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('idx_materials_warehouse', ['warehouse_id'], unique=False)

    op.create_table('mcp_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mcp_endpoint', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='operate', nullable=False),
    sa.Column('auto_start', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='stopped', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('restart_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_mcp_connections_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_mcp_connections_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_connections')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.create_index('idx_mcp_connections_tenant', ['tenant_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=191), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token', name=op.f('uq_sessions_token')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('tenant_face_operation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('require_face', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('allowed_subject_ids', sa.JSON(), nullable=True),
    sa.Column('min_confidence_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_face_operation_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_tenant_face_operation_rules_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_face_operation_rules')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('tenant_face_operation_rules', schema=None) as batch_op:
        batch_op.create_index('idx_face_rules_lookup', ['tenant_id', 'warehouse_id', 'operation'], unique=False)

    op.create_table('user_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_warehouses_user_id_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_user_warehouses_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_warehouses')),
    sa.UniqueConstraint('user_id', 'warehouse_id', name='uq_user_warehouses_user_id_warehouse_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('is_exhausted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('variant', sa.String(length=191), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_batches_contact_id_contacts')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_batches_material_id_materials')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_batches_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_batches_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('batch_no', name=op.f('uq_batches_batch_no')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('idx_batches_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('idx_batches_warehouse', ['warehouse_id'], unique=False)

    op.create_table('inventory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=64), server_default='系统', nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reason_category', sa.String(length=32), nullable=True),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('operator_user_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_inventory_records_batch_id_batches')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_inventory_records_contact_id_contacts')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_inventory_records_material_id_materials')),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], name=op.f('fk_inventory_records_operator_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_inventory_records_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_records_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_records')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('inventory_records', schema=None) as batch_op:
        batch_op.create_index('idx_records_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('idx_records_warehouse', ['warehouse_id'], unique=False)

    op.create_table('batch_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_consumptions_batch_id_batches')),
    sa.ForeignKeyConstraint(['record_id'], ['inventory_records.id'], name=op.f('fk_batch_consumptions_record_id_inventory_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_consumptions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_consumptions')
    with op.batch_alter_table('inventory_records', schema=None) as batch_op:
        batch_op.drop_index('idx_records_warehouse')
        batch_op.drop_index('idx_records_tenant')

    op.drop_table('inventory_records')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index('idx_batches_warehouse')
        batch_op.drop_index('idx_batches_tenant')

    op.drop_table('batches')
    op.drop_table('user_warehouses')
    with op.batch_alter_table('tenant_face_operation_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_face_rules_lookup')

    op.drop_table('tenant_face_operation_rules')
    op.drop_table('sessions')
    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_mcp_connections_tenant')

    op.drop_table('mcp_connections')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('idx_materials_warehouse')
        batch_op.drop_index('idx_materials_tenant')
        batch_op.drop_index('idx_materials_sku_wh')

    op.drop_table('materials')
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.drop_index('idx_face_enroll_subject')
        batch_op.drop_index('idx_face_enroll')

    op.drop_table('face_enrollments')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('idx_contacts_tenant')

    op.drop_table('contacts')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_api_keys_tenant')

    op.drop_table('api_keys')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('idx_warehouses_tenant')

    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_tenant')

    op.drop_table('users')
    op.drop_table('tenant_face_config')
    with op.batch_alter_table('face_subjects', schema=None) as batch_op:
        batch_op.drop_index('idx_face_subjects_tenant')

    op.drop_table('face_subjects')
    op.drop_table('erp_providers')
    op.drop_table('tenants')
    op.drop_table('system_settings')
    with op.batch_alter_table('face_auth_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_face_logs_query')

    op.drop_table('face_auth_logs')
    # ### end Alembic commands ###
